import type { NoticeItemData } from "../_types/notice";

export const INITIAL_NOTICES: NoticeItemData[] = [
  {
    id: 1,
    storeName: "별동네 베이커리카페 별내본점",
    title: "픽업 예정일은 2/30 19:00 입니다.",
    description: "픽업 날짜를 꼭 지켜주세요!",
    isRead: false,
  },
  {
    id: 2,
    storeName: "별동네 베이커리카페 별내본점",
    title: "금일 매장 사정으로 조기 마감합니다.",
    description: "방문 전 운영 여부를 꼭 확인해주세요.",
    isRead: false,
  },
  {
    id: 3,
    storeName: "별동네 베이커리카페 별내본점",
    title: "내부 점검으로 인해 잠시 영업이 중단됩니다.",
    description: "이용에 불편을 드려 죄송합니다.",
    isRead: false,
  },
  {
    id: 4,
    storeName: "별동네 베이커리카페 별내본점",
    title: "신메뉴 출시! 달콤한 신제품을 만나보세요.",
    description: "이번 주말까지 신메뉴 할인 이벤트도 진행 중입니다.",
    isRead: false,
  },
  {
    id: 5,
    storeName: "별동네 베이커리카페 별내본점",
    title: "매장 리뉴얼 공사 안내",
    description: "3월 1일부터 3월 10일까지 매장 리뉴얼 공사가 진행됩니다. 이용에 참고 부탁드립니다.",
    isRead: false,
  },
  {
    id: 6,
    storeName: "별동네 베이커리카페 별내본점",
    title: "정기 점검 안내",
    description: "매월 첫째 주 월요일은 정기 점검으로 인해 매장이 휴무입니다. 이용에 참고 부탁드립니다.",
    isRead: true,
  },
  {
    id: 7,
    storeName: "별동네 베이커리카페 별내본점",
    title: "고객 감사 이벤트",
    description: "이번 달 말까지 방문하시는 모든 고객님께 감사의 마음을 담아 특별한 혜택을 드립니다. 많은 관심 부탁드립니다.",
    isRead: true,
  },
  {
    id: 8,
    storeName: "별동네 베이커리카페 별내본점",
    title: "매장 이전 안내",
    description: "새로운 위치에서 더 나은 서비스를 제공하기 위해 매장을 이전합니다. 새로운 주소는 4월 1일부터 적용됩니다.",
    isRead: true,
  },
  {
    id: 9,
    storeName: "별동네 베이커리카페 별내본점",
    title: "신규 직원 채용 안내",
    description: "고객님께 더 나은 서비스를 제공하기 위해 신규 직원을 채용합니다. 관심 있는 분들의 많은 지원 바랍니다.",
    isRead: true,
  },
  {
    id: 10,
    storeName: "별동네 베이커리카페 별내본점",
    title: "매장 휴무 안내",
    description: "내부 사정으로 인해 5월 1일 매장이 휴무입니다. 이용에 참고 부탁드립니다.",
    isRead: true,
  },
  {
    id: 11,
    storeName: "별동네 베이커리카페 별내본점",
    title: "새로운 메뉴 출시",
    description: "더 맛있는 새로운 메뉴를 만나보세요!",
    isRead: true,
  },
  {
    id: 12,
    storeName: "별동네 베이커리카페 별내본점",
    title: "매장 리뉴얼 안내",
    description: "매장이 새롭게 리뉴얼됩니다. 더 나은 서비스로 찾아뵙겠습니다.",
    isRead: true,
  },
  {
    id: 13,
    storeName: "별동네 베이커리카페 별내본점",
    title: "고객 만족도 조사",
    description: "고객님의 소중한 의견을 듣기 위해 간단한 조사를 진행하고 있습니다. 참여해 주세요!",
    isRead: true,
  },
  {
    id: 14,
    storeName: "별동네 베이커리카페 별내본점",
    title: "정기 점검 안내",
    description: "매월 첫째 주 월요일은 정기 점검으로 인해 매장이 휴무입니다. 이용에 참고 부탁드립니다.",
    isRead: true,
  },
  {
    id: 15,
    storeName: "별동네 베이커리카페 별내본점",
    title: "새로운 이벤트 안내",
    description: "특별한 이벤트가 진행됩니다. 많은 관심 부탁드립니다.",
    isRead: true,
  },
  {
    id: 16,
    storeName: "별동네 베이커리카페 별내본점",
    title: "매장 이전 안내",
    description: "새로운 위치에서 더 나은 서비스를 제공하기 위해 매장을 이전합니다. 새로운 주소는 4월 1일부터 적용됩니다.",
    isRead: true,
  },
  {
    id: 17,
    storeName: "별동네 베이커리카페 별내본점",
    title: "신규 직원 채용 안내",
    description: "고객님께 더 나은 서비스를 제공하기 위해 신규 직원을 채용합니다. 관심 있는 분들의 많은 지원 바랍니다.",
    isRead: true,
  },
  {
    id: 18,
    storeName: "별동네 베이커리카페 별내본점",
    title: "매장 휴무 안내",
    description: "내부 사정으로 인해 5월 1일 매장이 휴무입니다. 이용에 참고 부탁드립니다.",
    isRead: true,
  },
  {
    id: 19,
    storeName: "별동네 베이커리카페 별내본점",
    title: "고객 감사 이벤트",
    description: "이번 달 말까지 방문하시는 모든 고객님께 감사의 마음을 담아 특별한 혜택을 드립니다. 많은 관심 부탁드립니다.",
    isRead: true,
  },
  {
    id: 20,
    storeName: "별동네 베이커리카페 별내본점",
    title: "새로운 메뉴 출시",
    description: "더 맛있는 새로운 메뉴를 만나보세요!",
    isRead: true,
  },
  {
    id: 21,
    storeName: "별동네 베이커리카페 별내본점",
    title: "매장 리뉴얼 안내",
    description: "매장이 새롭게 리뉴얼됩니다. 더 나은 서비스로 찾아뵙겠습니다.",
    isRead: true,
  },
  {
    id: 22, storeName: "별동네 베이커리카페 별내본점",
    title: "고객 만족도 조사",
    description: "고객님의 소중한 의견을 듣기 위해 간단한 조사를 진행하고 있습니다. 참여해 주세요!",
    isRead: true,
  },
  {
    id: 23, storeName: "별동네 베이커리카페 별내본점",
    title: "정기 점검 안내",
    description: "매월 첫째 주 월요일은 정기 점검으로 인해 매장이 휴무입니다. 이용에 참고 부탁드립니다.",
    isRead: true,
  },
  {
    id: 24, storeName: "별동네 베이커리카페 별내본점",
    title: "새로운 이벤트 안내",
    description: "특별한 이벤트가 진행됩니다. 많은 관심 부탁드립니다.",
    isRead: true,
  },
  {
    id: 25, storeName: "별동네 베이커리카페 별내본점",
    title: "매장 이전 안내",
    description: "새로운 위치에서 더 나은 서비스를 제공하기 위해 매장을 이전합니다. 새로운 주소는 4월 1일부터 적용됩니다.",
    isRead: true,
  }
];