import type { MainStoreItem } from "../_types/main-list";

export const MAIN_SORT_OPTIONS = ["가게 등록순", "가격순", "추천순"] as const;

export const MAIN_CATEGORY_TAGS = ["카페", "베이커리", "식당"] as const;

export const MOCK_MAIN_STORE_LIST: MainStoreItem[] = [
  {
    id: 1,
    itemName: "딸기 생크림 박스",
    categories: ["베이커리", "카페"],
    primaryCategory: "베이커리",
    storeName: "가톨릭대 정문 브레드하우스",
    address: "경기 부천시 지봉로 43 인근",
    latitude: 37.4869,
    longitude: 126.8013,
    startTime: "19:00",
    endTime: "21:00",
    openTime: "09:00",
    closeTime: "18:00",
    price: 5500,
    email: "breadhouse@gmail.com",
  },
  {
    id: 2,
    itemName: "수제 쿠키 랜덤박스",
    categories: ["베이커리"],
    primaryCategory: "베이커리",
    storeName: "부천역 카페 오븐데이",
    address: "경기 부천시 부일로 460 인근",
    latitude: 37.4848,
    longitude: 126.7836,
    startTime: "18:30",
    endTime: "20:30",
    openTime: "10:00",
    closeTime: "20:00",
    price: 4000,
    email: "ovenday@gmail.com",
  },
  {
    id: 3,
    itemName: "샌드위치 브런치팩",
    categories: ["카페", "식당"],
    primaryCategory: "식당",
    storeName: "역곡 브런치살롱",
    address: "경기 부천시 역곡로 8 인근",
    latitude: 37.4861,
    longitude: 126.8112,
    startTime: "10:00",
    endTime: "13:00",
    openTime: "09:30",
    closeTime: "19:30",
    price: 6900,
    email: "brunchsalon@gmail.com",
  },
  {
    id: 4,
    itemName: "소금빵 4종 박스",
    categories: ["베이커리", "카페"],
    primaryCategory: "베이커리",
    storeName: "역곡역 앞 솔트베이크",
    address: "경기 부천시 역곡로 3 인근",
    latitude: 37.4853,
    longitude: 126.8118,
    startTime: "17:00",
    endTime: "20:00",
    openTime: "08:30",
    closeTime: "19:30",
    price: 6000,
    email: "saltbake@gmail.com",
  },
  {
    id: 5,
    itemName: "오늘의 디저트팩",
    categories: ["카페"],
    primaryCategory: "카페",
    storeName: "가톨릭대 후문 모어커피",
    address: "경기 부천시 지봉로 50 인근",
    latitude: 37.4878,
    longitude: 126.8035,
    startTime: "20:00",
    endTime: "22:00",
    openTime: "09:00",
    closeTime: "22:00",
    price: 4500,
    email: "morecoffee@gmail.com",
  },
  {
    id: 6,
    itemName: "마카롱 혼합 박스",
    categories: ["베이커리", "카페"],
    primaryCategory: "카페",
    storeName: "부천 디저트랩",
    address: "경기 부천시 부일로 448 인근",
    latitude: 37.4856,
    longitude: 126.7862,
    startTime: "18:00",
    endTime: "21:00",
    openTime: "12:00",
    closeTime: "21:00",
    price: 7000,
    email: "dessertlab@gmail.com",
  },
  {
    id: 7,
    itemName: "한식 도시락 세트",
    categories: ["식당"],
    primaryCategory: "식당",
    storeName: "역곡 한끼식당",
    address: "경기 부천시 역곡로 22 인근",
    latitude: 37.4872,
    longitude: 126.8095,
    startTime: "13:00",
    endTime: "15:00",
    openTime: "10:30",
    closeTime: "20:30",
    price: 6500,
    email: "hankki@gmail.com",
  },
  {
    id: 8,
    itemName: "베이글 랜덤팩",
    categories: ["베이커리", "카페"],
    primaryCategory: "베이커리",
    storeName: "가톨릭대 베이글스팟",
    address: "경기 부천시 지봉로 59 인근",
    latitude: 37.4884,
    longitude: 126.8022,
    startTime: "16:00",
    endTime: "19:00",
    openTime: "08:00",
    closeTime: "17:00",
    price: 5200,
    email: "bagelspot@gmail.com",
  },
  {
    id: 9,
    itemName: "파스타 투고 박스",
    categories: ["식당", "카페"],
    primaryCategory: "식당",
    storeName: "부천 로컬키친",
    address: "경기 부천시 부일로 472 인근",
    latitude: 37.4842,
    longitude: 126.7847,
    startTime: "11:30",
    endTime: "14:00",
    openTime: "11:00",
    closeTime: "21:00",
    price: 7900,
    email: "localkitchen@gmail.com",
  },
  {
    id: 10,
    itemName: "조각케이크 랜덤팩",
    categories: ["카페", "베이커리"],
    primaryCategory: "카페",
    storeName: "역곡 스윗테이블",
    address: "경기 부천시 역곡로 15 인근",
    latitude: 37.4867,
    longitude: 126.8101,
    startTime: "19:30",
    endTime: "21:30",
    openTime: "10:00",
    closeTime: "22:00",
    price: 6000,
    email: "sweettable@gmail.com",
  },
];